[package]
name = "parallelSorting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.3", features = [] }  # Check https://crates.io/crates/rand for the latest version
